### PR TITLE
Remove conditional statement at line 173

### PR DESCRIPTION
**Pull request by lmhung**
Conditional statement at line 173 is not necessary, remove this conditional statement will make the plugin calculate and add CSS height property to every div.pxu-photo (1.7.0 and earlier versions did not add CSS height property to rows that have one images)

### CODE REVIEW

**Comment by graygilmore** [comment]
Rows with only one image shouldn't need to find the smallest height, hence the conditional. The problem was the lack of `display: block` on the images themselves which was fixed here: https://github.com/PixelUnion/Extended-Tumblr-Photoset/pull/14

Thanks for the heads up on the original bug!

**Comment by lmhung** [comment]
Adding smallest height could be useful, especially when using with Masonry, it will prevent divs with image from overlapping another while the site is processing.

**Comment by EvaRune** [comment]
Also add a problem with the statement at line 173, I had to remove it because it returned a height:0 value on webkit browsers (worked fine on firefox and IE, but not chrome or safari)

**Comment by EvaRune** [comment]
I tried to play with it but in Chrome, <code>smallestHeight</code> always returns 0 when I make a console log.

I reverted to the conditional used in 1.5.0 since it always worked for me, and I'm using imagesloaded anyway.

**Pull request closed without merging**
